### ISSUE TITLE
Signup Kosh+Feluda for paid projects

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/kosh-v2#69]
### Features : 
- [x] https://github.com/tattle-made/kosh-v2/issues/68
- [x] #70
- [ ] #71
- [ ] Scrape abstracts of Economic Journals
- [x] #75
- [x] https://github.com/tattle-made/kosh-v2/issues/72
- [x] https://github.com/tattle-made/feluda/issues/39
- [x] #76
- [x] #77
- [x] #80

**Comment by dennyabrain** [comment]
This has transformed into https://github.com/tattle-made/feluda/issues/482
